name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Render deploy
        run: |
          echo " Отправка запроса на Render..."
          curl -X POST "https://api.render.com/deploy/srv-d0g81ms9c44c73fbmtag?key=hRoqq2O5nm8"
          echo " Render начал деплой."
